# install system packages required by redis.
- name: install system packages required by redis
  yum:
    name:
      - tcl
    state: present
  tags:
    - install

# create redis directories in loop.
- name: create redis directories in loop
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    recurse: true
    mode: 0700
  loop:
    - "{{config_dir}}"
    - "{{system_dir}}"
    - "{{log_dir}}"
    - "{{data_dir}}"
  tags:
    - install

# download and extract redis.
- name: download and extract redis
  unarchive:
    src: http://download.redis.io/releases/redis-{{version}}.tar.gz
    dest: /tmp
    owner: root
    group: root
    remote_src: yes
    creates: /tmp/redis-{{version}}
  tags:
    - install

# compile and install redis from source.
- name: compile and install redis from source
  command: "{{item}}"
  args:
    chdir: /tmp/redis-{{version}}
  loop:
    - make distclean
    - make
    - make install
  tags:
    - install

# cleanup redis source.
- name: cleanup redis source
  file:
    path: /tmp/redis-{{version}}
    state: absent
    owner: root
    group: root
    mode: 0700
  tags:
    - install
