---
# Download and extracting redis package
- name: download and extract package
  command: "{{item}}"
  with_items:
   - cd /tmp
   - wget http://download.redis.io/releases/redis-{{version}}.tar.gz 
   - tar -xvzf redis-{{version}}.tar.gz
   - mv redis-{{version}} /var/lib/redis
   - rm redis-{{version}}.tar.gz
  when: not redis.stat.exists
# Compile and installing redis
- name: compile & install
  command: "{{item}}"
  args:
    chdir: /var/lib/redis
  with_items:
    - make
    - make install
  notify: 
    - start redis